development:
  adapter: postgresql
  database: prelaunchr_development
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: prelaunchr_test
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["POSTGRESQL_ADDON_DB"] %>
  host: <%= ENV["POSTGRESQL_ADDON_HOST"] %>
  username: <%= ENV["POSTGRESQL_ADDON_USER"] %>
  password: <%= ENV["POSTGRESQL_ADDON_PASSWORD"] %>
  port: <%= ENV["POSTGRESQL_ADDON_PORT"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
